# Generated by Django 4.0.4 on 2022-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
