# Generated by Django 4.0.4 on 2022-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.TextField(max_length=120),
        ),
    ]
