# Generated by Django 4.0.4 on 2022-05-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_content_alter_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='price',
        ),
    ]
